//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace formulario.WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name ToStringResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ToString", ReplyAction="*")]
        formulario.WS.ToStringResponse ToString(formulario.WS.ToStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ToString", ReplyAction="*")]
        System.Threading.Tasks.Task<formulario.WS.ToStringResponse> ToStringAsync(formulario.WS.ToStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToString", Namespace="http://tempuri.org/", Order=0)]
        public formulario.WS.ToStringRequestBody Body;
        
        public ToStringRequest() {
        }
        
        public ToStringRequest(formulario.WS.ToStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ToStringRequestBody {
        
        public ToStringRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public formulario.WS.ToStringResponseBody Body;
        
        public ToStringResponse() {
        }
        
        public ToStringResponse(formulario.WS.ToStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ToStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ToStringResult;
        
        public ToStringResponseBody() {
        }
        
        public ToStringResponseBody(string ToStringResult) {
            this.ToStringResult = ToStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : formulario.WS.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<formulario.WS.WebServiceSoap>, formulario.WS.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        formulario.WS.ToStringResponse formulario.WS.WebServiceSoap.ToString(formulario.WS.ToStringRequest request) {
            return base.Channel.ToString(request);
        }
        
        public string ToString() {
            formulario.WS.ToStringRequest inValue = new formulario.WS.ToStringRequest();
            inValue.Body = new formulario.WS.ToStringRequestBody();
            formulario.WS.ToStringResponse retVal = ((formulario.WS.WebServiceSoap)(this)).ToString(inValue);
            return retVal.Body.ToStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<formulario.WS.ToStringResponse> formulario.WS.WebServiceSoap.ToStringAsync(formulario.WS.ToStringRequest request) {
            return base.Channel.ToStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<formulario.WS.ToStringResponse> ToStringAsync() {
            formulario.WS.ToStringRequest inValue = new formulario.WS.ToStringRequest();
            inValue.Body = new formulario.WS.ToStringRequestBody();
            return ((formulario.WS.WebServiceSoap)(this)).ToStringAsync(inValue);
        }
    }
}
