//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_WEB_SERVICES.Convertidor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Convertidor.ConvertSoap")]
    public interface ConvertSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TP_WEB_SERVICES.Convertidor.HelloWorldResponse HelloWorld(TP_WEB_SERVICES.Convertidor.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_WEB_SERVICES.Convertidor.HelloWorldResponse> HelloWorldAsync(TP_WEB_SERVICES.Convertidor.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name u1 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Convertir", ReplyAction="*")]
        TP_WEB_SERVICES.Convertidor.ConvertirResponse Convertir(TP_WEB_SERVICES.Convertidor.ConvertirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Convertir", ReplyAction="*")]
        System.Threading.Tasks.Task<TP_WEB_SERVICES.Convertidor.ConvertirResponse> ConvertirAsync(TP_WEB_SERVICES.Convertidor.ConvertirRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TP_WEB_SERVICES.Convertidor.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TP_WEB_SERVICES.Convertidor.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_WEB_SERVICES.Convertidor.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TP_WEB_SERVICES.Convertidor.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Convertir", Namespace="http://tempuri.org/", Order=0)]
        public TP_WEB_SERVICES.Convertidor.ConvertirRequestBody Body;
        
        public ConvertirRequest() {
        }
        
        public ConvertirRequest(TP_WEB_SERVICES.Convertidor.ConvertirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double n1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string u1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string u2;
        
        public ConvertirRequestBody() {
        }
        
        public ConvertirRequestBody(double n1, string u1, string u2) {
            this.n1 = n1;
            this.u1 = u1;
            this.u2 = u2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertirResponse", Namespace="http://tempuri.org/", Order=0)]
        public TP_WEB_SERVICES.Convertidor.ConvertirResponseBody Body;
        
        public ConvertirResponse() {
        }
        
        public ConvertirResponse(TP_WEB_SERVICES.Convertidor.ConvertirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double ConvertirResult;
        
        public ConvertirResponseBody() {
        }
        
        public ConvertirResponseBody(double ConvertirResult) {
            this.ConvertirResult = ConvertirResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConvertSoapChannel : TP_WEB_SERVICES.Convertidor.ConvertSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertSoapClient : System.ServiceModel.ClientBase<TP_WEB_SERVICES.Convertidor.ConvertSoap>, TP_WEB_SERVICES.Convertidor.ConvertSoap {
        
        public ConvertSoapClient() {
        }
        
        public ConvertSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvertSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_WEB_SERVICES.Convertidor.HelloWorldResponse TP_WEB_SERVICES.Convertidor.ConvertSoap.HelloWorld(TP_WEB_SERVICES.Convertidor.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TP_WEB_SERVICES.Convertidor.HelloWorldRequest inValue = new TP_WEB_SERVICES.Convertidor.HelloWorldRequest();
            inValue.Body = new TP_WEB_SERVICES.Convertidor.HelloWorldRequestBody();
            TP_WEB_SERVICES.Convertidor.HelloWorldResponse retVal = ((TP_WEB_SERVICES.Convertidor.ConvertSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_WEB_SERVICES.Convertidor.HelloWorldResponse> TP_WEB_SERVICES.Convertidor.ConvertSoap.HelloWorldAsync(TP_WEB_SERVICES.Convertidor.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_WEB_SERVICES.Convertidor.HelloWorldResponse> HelloWorldAsync() {
            TP_WEB_SERVICES.Convertidor.HelloWorldRequest inValue = new TP_WEB_SERVICES.Convertidor.HelloWorldRequest();
            inValue.Body = new TP_WEB_SERVICES.Convertidor.HelloWorldRequestBody();
            return ((TP_WEB_SERVICES.Convertidor.ConvertSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TP_WEB_SERVICES.Convertidor.ConvertirResponse TP_WEB_SERVICES.Convertidor.ConvertSoap.Convertir(TP_WEB_SERVICES.Convertidor.ConvertirRequest request) {
            return base.Channel.Convertir(request);
        }
        
        public double Convertir(double n1, string u1, string u2) {
            TP_WEB_SERVICES.Convertidor.ConvertirRequest inValue = new TP_WEB_SERVICES.Convertidor.ConvertirRequest();
            inValue.Body = new TP_WEB_SERVICES.Convertidor.ConvertirRequestBody();
            inValue.Body.n1 = n1;
            inValue.Body.u1 = u1;
            inValue.Body.u2 = u2;
            TP_WEB_SERVICES.Convertidor.ConvertirResponse retVal = ((TP_WEB_SERVICES.Convertidor.ConvertSoap)(this)).Convertir(inValue);
            return retVal.Body.ConvertirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TP_WEB_SERVICES.Convertidor.ConvertirResponse> TP_WEB_SERVICES.Convertidor.ConvertSoap.ConvertirAsync(TP_WEB_SERVICES.Convertidor.ConvertirRequest request) {
            return base.Channel.ConvertirAsync(request);
        }
        
        public System.Threading.Tasks.Task<TP_WEB_SERVICES.Convertidor.ConvertirResponse> ConvertirAsync(double n1, string u1, string u2) {
            TP_WEB_SERVICES.Convertidor.ConvertirRequest inValue = new TP_WEB_SERVICES.Convertidor.ConvertirRequest();
            inValue.Body = new TP_WEB_SERVICES.Convertidor.ConvertirRequestBody();
            inValue.Body.n1 = n1;
            inValue.Body.u1 = u1;
            inValue.Body.u2 = u2;
            return ((TP_WEB_SERVICES.Convertidor.ConvertSoap)(this)).ConvertirAsync(inValue);
        }
    }
}
