//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_CreaciónControlesUsuario
{


    public partial class FormularioPruebaControles
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Table1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Table Table1;

        /// <summary>
        /// TextBoxNoEmpty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TP_CreaciónControlesUsuario.ControlesUsuario.TextBoxNoEmpty TextBoxNoEmpty;

        /// <summary>
        /// TextBoxNoEmpty1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TP_CreaciónControlesUsuario.ControlesUsuario.TextBoxNoEmpty TextBoxNoEmpty1;

        /// <summary>
        /// TextBoxCuit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TP_CreaciónControlesUsuario.ControlesUsuario.TextBoxCuit TextBoxCuit;

        /// <summary>
        /// TexBoxMayorEdad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TP_CreaciónControlesUsuario.ControlesUsuario.TexBoxMayorEdad TexBoxMayorEdad;

        /// <summary>
        /// RadioButtonSex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TP_CreaciónControlesUsuario.ControlesUsuario.RadioButtonSex RadioButtonSex;

        /// <summary>
        /// ComboPaises control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TP_CreaciónControlesUsuario.ControlesUsuario.ComboPaises ComboPaises;

        /// <summary>
        /// RangoHijosMenores control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TP_CreaciónControlesUsuario.ControlesUsuario.RangoHijosMenores RangoHijosMenores;

        /// <summary>
        /// Button1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button1;
    }
}
